alias: Update Servos with Temperature
description: ""
trigger:
  - platform: state
    entity_id: sensor.weather_station_temperature
action:
  - service: esphome.digital_thermometer_set_servo_positions
    data_template:
      position: >-
        {{ states('sensor.weather_station_temperature') | float | round(0) | int
        }}
